### PR TITLE
Add print circuit method

### PR DESCRIPTION
**Pull request by danbev**
### Summary
This commit introduces a print method to the Circuit class. The idea is
to give a visual representation of the quantum circuit.

### Details and comments
The motivation for this is as a learning aid to help understand the
circuit created. The implementation can probably be made more efficient
but I wanted to get some feedback on this feature and if it is
worth pursuing/spending time on (or perhaps it could be useful as is
and developed further as required).

<details>
<summary>Node REPL example:</summary>

```console
> const { Circuit, Gate } = require('./index.js');
undefined

> const c = Circuit.createCircuit(1);
undefined
> c.addGate(Gate.x, 0, 0).print()

          column 0
wire 0 ---[x]-----------

undefined
> c.addGate(Gate.cx, 1, [0, 1]).print()

          column 0      column 1
wire 0 ---[x]-----------[cx]----------
                         |
wire 1 -----------------[*]-----------
 ```
</details>

<details>
<summary>Node example:</summary>

```js
const { Circuit, Gate } = require('./index.js');
const c = Circuit.createCircuit(2);
c.addGate(Gate.x, 0, 0).print()
c.addGate(Gate.cx, 1, [0, 1]).print()
```

```console
$ node example

          column 0
wire 0 ---[x]-----------

wire 1 -----------------


          column 0      column 1
wire 0 ---[x]-----------[cx]----------
                         |
wire 1 -----------------[*]-----------
```
</details>

### CODE REVIEW

**Comment by danbev** [comment]
CI [failures](https://travis-ci.com/Qiskit/qiskit-js/builds/110363512#L720) happen to me locally on the master branch. I've not seen this before but perhaps others have?

**Comment by omarcostahamido** [comment]
nice implementation, @danbev .
No idea regarding the Travis CI error. Do you want to give it another try to create the pull request?

O

**Comment by danbev** [comment]
@omarcostahamido The tests are now passing for me locally on the master branch so hopefully this should just be a matter of re-running the Travis build (I don't have the rights to do so). I can force push which should trigger it too I think but I'll hold off a little before doing so.

**Comment by jesusprubio** [comment]
Sorry I was travelling. I will check because it happens from time to time, maybe with a little retry setup we could avoid it.

BTW, really nice PR, thanks :smile:

**Pull request merged**
