### PR TITLE
Add createCircuit factory function

### PR DESCRIPTION
**Pull request by danbev**
### Summary
This commit adds a factory function named createCircuit that takes the
number of qubits as its sole argument.

### Details and comments
The motivation for this is that I've found myself trying to create a new
circuit using new Circuit(3). Having this function allows for just
passing in the number of qubits.

### CODE REVIEW

**Comment by jesusprubio** [comment]
Thank you! :). Please let me know when you consider we need a new npm release. I don't know the next improvements you have in mind.

**Comment by danbev** [comment]
> Please let me know when you consider we need a new npm release.

It would be nice to have a new release soon as I can start using some of these features. Thanks



> I don't know the next improvements you have in mind.

I'm not sure either :). But I'll continue using/playing and see if there are any suggestions that might pop up.

**Comment by jesusprubio** [comment]
Published, thank you :)

https://github.com/Qiskit/qiskit-js/releases/tag/v0.6.3

**Comment by danbev** [comment]
>Published, thank you :)

Awesome, thanks!

**Pull request merged**
